import type { GalleryImageData } from './images'

// ── Gallery Images ─────────────────────────────────────────────────────────
// Used on: Home page (gallery grid), Gallery page (masonry + lightbox),
//          Contact page (hero & CTA backgrounds)

export const GALLERY_IMAGES: GalleryImageData[] = [
  {
    src: '/images/gallery/Ambiance/Ambiance-1.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-1.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Coupes/Coupes-1.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Outils/Outils-1.jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-1.jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers-2.jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-1.jpeg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Outils/Outils-2.jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-2.jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-2.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'tall',
  },
  {
    src: '/images/gallery/Outils/Outils-3.jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-3.jpeg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'tall',
  },
  {
    src: '/images/gallery/Soins/Soins-3.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-4.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers-4.jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-2.jpeg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'wide',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-5.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers-5.jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-6.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'tall',
  },
  {
    src: '/images/gallery/Outils/Outils-6.jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'wide',
  },
  {
    src: '/images/gallery/Salon/Salon-3.jpeg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-12.jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'wide',
  },
  {
    src: '/images/gallery/Soins/Soins-7.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-8.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Outils/Outils-8.jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-4.jpeg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-8.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-9.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'tall',
  },
  {
    src: '/images/gallery/Outils/Outils-9.jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-14.jpeg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'wide',
  },
  {
    src: '/images/gallery/Soins/Soins-9.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-10.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-10.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'wide',
  },
  {
    src: '/images/gallery/Outils/Outils-10.jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-15.jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-5.jpeg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-10.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-11.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'tall',
  },
  {
    src: '/images/gallery/Coupes/Coupes-11.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-5.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-11.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'wide',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-12.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-12.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-13.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-13.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-13.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-7.jpeg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-13.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'tall',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-14.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-14.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-7.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'wide',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-15.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-15.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-8.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'tall',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-16.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'wide',
  },
  {
    src: '/images/gallery/Salon/Salon-9.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-17.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-17.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-10.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-18.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-18.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-11.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-19.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Coupes/Coupes-19.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'wide',
  },
  {
    src: '/images/gallery/Salon/Salon-12.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-20.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-20.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-13.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'tall',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-21.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-21.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-21.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-22.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-22.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-23.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'wide',
  },
  {
    src: '/images/gallery/Barbe/Barbe-23.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-23.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-16.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-24.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-25.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-18.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'wide',
  },
  {
    src: '/images/gallery/Barbe/Barbe-26.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-19.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-27.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes-28.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-30.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-31.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-33.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-34.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-36.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-37.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-38.png',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-39.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-40.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-41.png',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-42.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-43.png',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-44.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-45.png',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-46.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-47.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-48.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-49.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-50.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-51.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-52.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-53.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-54.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-55.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-56.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-57.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-58.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-59.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-60.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-61.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-62.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-63.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-64.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-65.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-66.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-67.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-68.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-16.jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-17.jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-18.jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-19.jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-20.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-21.png',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-22.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-23.png',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-24.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-25.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-26.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-27.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-28.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-29.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-14.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-15.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-16.png',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
]
