import type { GalleryImageData } from './images'

// ── Gallery Images ─────────────────────────────────────────────────────────
// Used on: Home page (gallery grid), Gallery page (masonry + lightbox),
//          Contact page (hero & CTA backgrounds)

export const GALLERY_IMAGES: GalleryImageData[] = [
  {
    src: '/images/gallery/Ambiance/Ambiance-1.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-1.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers-1.jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes-1.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Outils/Outils-1.jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-1.jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-1.jpeg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-1.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'tall',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-2.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-2.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers-2.jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-2.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'wide',
  },
  {
    src: '/images/gallery/Outils/Outils-2.jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-2.jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-1.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-2.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'tall',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-3.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'wide',
  },
  {
    src: '/images/gallery/Barbe/Barbe-3.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers-3.jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-3.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Outils/Outils-3.jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-3.jpeg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'tall',
  },
  {
    src: '/images/gallery/Salon/Salon-1.png',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-3.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-4.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-4.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'wide',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers-4.jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-4.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Outils/Outils-4.jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-4.jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'tall',
  },
  {
    src: '/images/gallery/Salon/Salon-2.jpeg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'wide',
  },
  {
    src: '/images/gallery/Soins/Soins-4.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-5.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-5.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers-5.jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-5.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'tall',
  },
  {
    src: '/images/gallery/Outils/Outils-5.jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-10.jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-2.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-5.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'wide',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-6.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-6.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers-6.jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-6.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'tall',
  },
  {
    src: '/images/gallery/Outils/Outils-6.jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'wide',
  },
  {
    src: '/images/gallery/Produit/Produit-11.jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-3.jpeg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-6.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-7.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-7.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers-7.jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-7.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Outils/Outils-7.jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-12.jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'wide',
  },
  {
    src: '/images/gallery/Salon/Salon-3.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-7.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-8.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-8.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Coupes/Coupes-8.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'wide',
  },
  {
    src: '/images/gallery/Outils/Outils-8.jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-13.jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-4.jpeg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-8.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-9.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'tall',
  },
  {
    src: '/images/gallery/Barbe/Barbe-9.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-9.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Outils/Outils-9.jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-14.jpeg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'wide',
  },
  {
    src: '/images/gallery/Salon/Salon-4.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-9.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-10.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-10.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Coupes/Coupes-10.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'wide',
  },
  {
    src: '/images/gallery/Outils/Outils-10.jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit-15.jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-5.jpeg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-10.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-11.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'tall',
  },
  {
    src: '/images/gallery/Barbe/Barbe-11.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-11.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-5.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-11.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'wide',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-12.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-12.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-12.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-6.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'tall',
  },
  {
    src: '/images/gallery/Soins/Soins-12.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'wide',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-13.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-13.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-13.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-7.jpeg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins-13.jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'tall',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-14.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-14.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-14.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-7.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'wide',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-15.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-15.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-15.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-8.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'tall',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-16.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'wide',
  },
  {
    src: '/images/gallery/Barbe/Barbe-16.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-9.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-17.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-17.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Coupes/Coupes-17.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-10.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-18.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-18.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes-18.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-11.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-19.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-19.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Coupes/Coupes-19.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'wide',
  },
  {
    src: '/images/gallery/Salon/Salon-12.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-20.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-20.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-20.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-13.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'tall',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-21.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-21.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-21.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-14.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'wide',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-22.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-22.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-22.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-15.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'tall',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance-23.jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'wide',
  },
  {
    src: '/images/gallery/Barbe/Barbe-23.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-23.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-16.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-24.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-24.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'tall',
  },
  {
    src: '/images/gallery/Salon/Salon-17.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-25.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-25.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-18.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'wide',
  },
  {
    src: '/images/gallery/Barbe/Barbe-26.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-26.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon-19.jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-27.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Coupes/Coupes-27.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'wide',
  },
  {
    src: '/images/gallery/Barbe/Barbe-28.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-28.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-29.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-29.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-30.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Coupes/Coupes-30.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe-31.jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-31.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-32.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes-33.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-34.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes-35.jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
]
