// ═══════════════════════════════════════════════════════════════════════════
// CENTRALIZED IMAGE REGISTRY
// Single source of truth for all images used across the website.
// Update paths or alt texts here to reflect changes everywhere.
// ═══════════════════════════════════════════════════════════════════════════

// ── Types ──────────────────────────────────────────────────────────────────

export interface ImageData {
  src: string
  alt: string
}

export interface GalleryImageData extends ImageData {
  /** Category for filtering on the gallery page */
  category: 'Coupes' | 'Barbe' | 'Ambiance' | 'Barbiers' | 'Outils' | 'Produit' | 'Salon' | 'Soins'
  /** Grid layout span on the gallery page */
  span: 'normal' | 'tall' | 'wide'
  /** Short alt used on the home page gallery grid */
  shortAlt: string
}

export interface TeamMemberImage extends ImageData {
  name: string
  role: string
  experience: string
}

// ── Logos ──────────────────────────────────────────────────────────────────

export const LOGOS = {
  header: {
    src: '/logo/logo-header.svg',
    alt: "L'Instant Barbier",
  },
  golden: {
    src: '/logo/logo-golden.svg',
    alt: "L'Instant Barbier",
  },
  black: {
    src: '/logo/logo-black.svg',
    alt: "L'Instant Barbier",
  },
  linstant: {
    src: '/logo/linstant-barbier-logo.png',
    alt: "L'Instant Barbier Logo",
  },
} as const satisfies Record<string, ImageData>

// ── Video ──────────────────────────────────────────────────────────────────

export const VIDEO = {
  aboutSection: {
    src: "/video/l'instant-barbier-paris.mp4",
    type: 'video/mp4',
  },
} as const

// ── Gallery Images ─────────────────────────────────────────────────────────
// Used on: Home page (gallery grid), Gallery page (masonry + lightbox),
//          Contact page (hero & CTA backgrounds)

export const GALLERY_IMAGES: GalleryImageData[] = [
  {
    src: '/images/gallery/Coupes/Coupes (1).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (1).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (1).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers- (1).jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'wide',
  },
  {
    src: '/images/gallery/Outils/Outils (1).jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit (1).jpeg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (1).jpeg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins (1).jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (10).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'tall',
  },
  {
    src: '/images/gallery/Barbe/Barbe (10).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (10).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers- (1).png',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'wide',
  },
  {
    src: '/images/gallery/Outils/Outils (1).png',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit (1).jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'tall',
  },
  {
    src: '/images/gallery/Salon/Salon (1).jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins (10).jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes (11).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (11).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (11).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers- (13).jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'normal',
  },
  {
    src: '/images/gallery/Outils/Outils (10).jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'tall',
  },
  {
    src: '/images/gallery/Produit/Produit (2).jpeg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (1).png',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins (11).jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes (12).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (12).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (12).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers- (14).JPG',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'wide',
  },
  {
    src: '/images/gallery/Outils/Outils (11).jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit (2).jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (10).JPG',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins (12).jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (13).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'tall',
  },
  {
    src: '/images/gallery/Barbe/Barbe (13).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (13).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers- (15).jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'wide',
  },
  {
    src: '/images/gallery/Outils/Outils (12).jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit (3).jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'tall',
  },
  {
    src: '/images/gallery/Salon/Salon (11).JPG',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins (13).jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes (14).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (14).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (14).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers- (16).jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'normal',
  },
  {
    src: '/images/gallery/Outils/Outils (13).jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'tall',
  },
  {
    src: '/images/gallery/Produit/Produit (4).jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (12).JPG',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins (14).jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes (15).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (15).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (15).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers- (17).jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'wide',
  },
  {
    src: '/images/gallery/Outils/Outils (2).jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit (5).JPG',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (13).jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins (2).jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (16).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'tall',
  },
  {
    src: '/images/gallery/Barbe/Barbe (16).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (16).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers- (18).jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'wide',
  },
  {
    src: '/images/gallery/Outils/Outils (3).jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit (6).JPG',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'tall',
  },
  {
    src: '/images/gallery/Salon/Salon (14).jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins (3).jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes (17).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (17).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (17).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers- (19).jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'normal',
  },
  {
    src: '/images/gallery/Outils/Outils (4).jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'tall',
  },
  {
    src: '/images/gallery/Produit/Produit (7).JPG',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (15).jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins (4).jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes (18).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (18).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (18).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers- (20).jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'wide',
  },
  {
    src: '/images/gallery/Outils/Outils (5).jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit (8).jpg',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (16).jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins (5).jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (19).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'tall',
  },
  {
    src: '/images/gallery/Barbe/Barbe (19).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (19).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers- (21).jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'wide',
  },
  {
    src: '/images/gallery/Outils/Outils (6).jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Produit/Produit (9).JPG',
    alt: 'Produit',
    shortAlt: 'Produit',
    category: 'Produit',
    span: 'tall',
  },
  {
    src: '/images/gallery/Salon/Salon (17).jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins (6).jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes (2).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (2).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (2).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers- (22).jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'normal',
  },
  {
    src: '/images/gallery/Outils/Outils (7).jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'tall',
  },
  {
    src: '/images/gallery/Salon/Salon (18).jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins (7).jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (20).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'wide',
  },
  {
    src: '/images/gallery/Barbe/Barbe (20).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (20).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'tall',
  },
  {
    src: '/images/gallery/Barbiers/Barbiers- (23).jpg',
    alt: 'Barbiers',
    shortAlt: 'Barbiers',
    category: 'Barbiers',
    span: 'normal',
  },
  {
    src: '/images/gallery/Outils/Outils (8).jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'wide',
  },
  {
    src: '/images/gallery/Salon/Salon (19).jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins (8).jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (21).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (21).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (21).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'tall',
  },
  {
    src: '/images/gallery/Outils/Outils (9).jpg',
    alt: 'Outils',
    shortAlt: 'Outils',
    category: 'Outils',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (2).jpeg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Soins/Soins (9).jpg',
    alt: 'Soins',
    shortAlt: 'Soins',
    category: 'Soins',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes (22).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (22).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (22).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (2).jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes (23).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (23).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (23).JPG',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (3).jpeg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (24).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'tall',
  },
  {
    src: '/images/gallery/Barbe/Barbe (24).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (24).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (3).jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes (25).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (25).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (25).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (4).jpeg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes (26).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (26).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (26).JPG',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (4).jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (27).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'tall',
  },
  {
    src: '/images/gallery/Barbe/Barbe (27).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (27).JPG',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (5).jpeg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes (28).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (28).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (28).JPG',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (5).jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes (29).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (29).JPG',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (29).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (6).jpeg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (3).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'tall',
  },
  {
    src: '/images/gallery/Barbe/Barbe (3).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (3).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (6).jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes (31).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (30).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (4).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (7).jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes (32).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (31).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (5).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (8).jpg',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (33).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'tall',
  },
  {
    src: '/images/gallery/Barbe/Barbe (32).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (6).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Salon/Salon (9).JPG',
    alt: 'Salon',
    shortAlt: 'Salon',
    category: 'Salon',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes (34).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (33).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (7).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (35).JPG',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'wide',
  },
  {
    src: '/images/gallery/Barbe/Barbe (34).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (8).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (38).JPG',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (35).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Ambiance/Ambiance (9).jpg',
    alt: 'Ambiance',
    shortAlt: 'Ambiance',
    category: 'Ambiance',
    span: 'tall',
  },
  {
    src: '/images/gallery/Coupes/Coupes (39).JPG',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (36).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (4).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'wide',
  },
  {
    src: '/images/gallery/Barbe/Barbe (4).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (40).JPG',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'tall',
  },
  {
    src: '/images/gallery/Barbe/Barbe (5).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (41).JPG',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'wide',
  },
  {
    src: '/images/gallery/Barbe/Barbe (6).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (42).JPG',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (7).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (43).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (8).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'tall',
  },
  {
    src: '/images/gallery/Coupes/Coupes (44).JPG',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Barbe/Barbe (9).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (45).JPG',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'wide',
  },
  {
    src: '/images/gallery/Barbe/Coupes (37).jpg',
    alt: 'Barbe',
    shortAlt: 'Barbe',
    category: 'Barbe',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (46).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'tall',
  },
  {
    src: '/images/gallery/Coupes/Coupes (47).JPG',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (48).JPG',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'wide',
  },
  {
    src: '/images/gallery/Coupes/Coupes (49).JPG',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (5).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (6).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (7).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
  {
    src: '/images/gallery/Coupes/Coupes (8).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'tall',
  },
  {
    src: '/images/gallery/Coupes/Coupes (9).jpg',
    alt: 'Coupes',
    shortAlt: 'Coupes',
    category: 'Coupes',
    span: 'normal',
  },
]

// ── Team ───────────────────────────────────────────────────────────────────

export const TEAM: TeamMemberImage[] = [
  {
    src: '/images/team/Riccardo.JPG',
    alt: "Riccardo — Coiffeur-barbier chez L'Instant Barbier",
    name: 'RICCARDO',
    role: 'Coiffeur-barbier et directeur artistique',
    experience: "23 ans d'expérience",
  },
]

// ── Product / Equipment Grid ─────────────────────────────────────────────
// Used on: Home page — À propos section (4-column product grid)

export const PRODUCT_GRID: ImageData[] = [
  {
    src: '/images/barbershop-equipments.jpg',
    alt: 'Équipements professionnels de barbier',
  },
  {
    src: '/images/barbershop-premium-products.jpg',
    alt: 'Produits premium pour homme',
  },
  {
    src: '/images/barbershop-face-cream.jpg',
    alt: 'Crème visage homme haut de gamme',
  },
  {
    src: '/images/barbershop-hair-products.jpeg',
    alt: 'Produits capillaires professionnels',
  },
]

// ── Page Heroes & Backgrounds ────────────────────────────────────────────
// Centralized background images used across pages.
// Keys are named by page + section for easy identification.

export const BACKGROUNDS = {
  // ── Home page ──
  homeHero: {
    src: '/images/hero-barbershop.jpg',
    alt: "L'Instant Barbier — salon de coiffure et barbier à Paris",
  },
  homeAtmosphere: {
    src: '/images/atmosphere.jpg',
    alt: 'Atmosphère élégante du salon',
  },
  homeInterior: {
    src: '/images/salon-interior-1.jpg',
    alt: "Intérieur du salon L'Instant Barbier",
  },
  homeSchedule: {
    src: '/images/salon-interior-2.jpg',
    alt: 'Vue du salon — horaires',
  },
  homeMap: {
    src: '/images/marais-paris.jpg',
    alt: 'Le Marais, Paris 3ème',
  },
  homeCta: {
    src: '/images/barber-tools-luxury.jpg',
    alt: 'Outils de barbier haut de gamme',
  },

  // ── Prestations page ──
  prestationsHero: {
    src: '/images/prestation-bg.jpg',
    alt: "Prestations L'Instant Barbier",
  },

  // ── Contact page (uses gallery images) ──
  contactHero: {
    src: '/images/prestation/sur-rdv.jpg',
    alt: "L'Instant barbier Paris 3 Marais",
  },
  contactCta: {
    src: '/images/contact/contact-cta.jpg',
    alt: "Prendre rendez-vous à L'Instant Barbier",
  },

  // ── Salon page (placeholders — replace with real images) ──
  salonHero: {
    src: '/images/salon/salon-l-instant-barbier.jpg',
    alt: "Salon L'Instant Barbier",
  },
  salonAtmosphereMain: {
    src: '/images/salon/interieur-du-salon-barbier.jpg',
    alt: 'Intérieur du salon',
  },
  salonAtmosphereDetail: {
    src: '/images/salon/detail-ambiance.jpg',
    alt: 'Détail ambiance',
  },
  salonExpertise: {
    src: '/images/salon/barbier-action.jpg',
    alt: 'Barbier en action',
  },
  salonExperienceLarge: {
    src: '/images/salon/salon-experience.jpg',
    alt: 'Expérience premium',
  },
  salonExperienceSmall1: {
    src: '/images/salon/salon-consultation.jpg',
    alt: 'Consultation',
  },
  salonExperienceSmall2: {
    src: '/images/salon/salon-relaxation-1.jpg',
    alt: 'Relaxation',
  },
  salonLocation: {
    src: '/images/salon/instant-barbier-salon.jpg',
    alt: 'Le Marais, Paris',
  },

  // ── Prestations page (placeholders — replace with real images) ──
  prestationCoiffure: {
    src: '/images/prestation/coiffure-homme.jpg',
    alt: 'Coiffure Homme',
  },
  prestationBarbe: {
    src: '/images/prestation/prestation-barbe.jpg',
    alt: 'Barbe',
  },
  prestationSoins: {
    src: '/images/prestation/prestation-soins.jpg',
    alt: 'Soins & Bien-être',
  },
  prestationBentoLarge: {
    src: '/images/prestation/prestation-large.jpg',
    alt: 'Expérience haut de gamme',
  },
  prestationBentoRendezVous: {
    src: '/images/prestation/sur-rdv.jpg',
    alt: 'Sur Rendez-vous',
  },
  prestationBentoPremium: {
    src: '/images/prestation/premium-products.jpg',
    alt: 'Produits Premium',
  },
  prestationCta: {
    src: '/images/prestation/prestation-cta.jpg',
    alt: 'Background',
  },
} as const satisfies Record<string, ImageData>
